import { Rarity } from "./TMCore/WAILA";

export const Config = {
    app_width: 1920,
    app_height: 1080,

    game_width: 1920,
    game_height: 1080,

    map_scale: 1,
    min_scale: 1,
    max_scale: 7,
    tiles_count_width: 10,
    tiles_count_height: 10,

    map_static_width: 0,
    map_static_height: 0,

    player_scale: 1,

    inventoryCellBorder: 5, // WHY IS IT HERE

    plants: [
        {
            tileset: "FarmingPlants",
            name: "Wheat",
            description: "Cereal gown",
            id: 10,
            growTime: 1000,
            rarity: Rarity.Common,
            drop: 0,
            animation: [11, 12, 13],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 15,
            growTime: 1000,
            rarity: Rarity.Common,
            drop: 1,
            animation: [16, 17, 18],
        },
        {
            tileset: "FarmingPlants",
            name: "Blue",
            description: "non",
            id: 20,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 2,
            animation: [21, 22, 23],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 25,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 3,
            animation: [26, 27, 28],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 30,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 4,
            animation: [31, 32, 33],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 35,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 5,
            animation: [36, 37, 38],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 40,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 6,
            animation: [41, 42, 43],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 45,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 7,
            animation: [46, 47, 48],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 50,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 8,
            animation: [51, 52, 53],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 55,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 9,
            animation: [56, 57, 58],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 60,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 10,
            animation: [61, 62, 63],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 65,
            growTime: 2000,
            rarity: Rarity.Mythic,
            drop: 11,
            animation: [66, 67, 68],
        },
        {
            tileset: "FarmingPlants",
            name: "Eggplant",
            description: "Plant species",
            id: 70,
            growTime: 2000,
            rarity: Rarity.Common,
            drop: 12,
            animation: [71, 72, 73],
        },
    ],

    drops: [
        {
            tileset: "Allitems",
            name: "Wheat",
            description: "Cereal gown",
            id: 17,
            rarity: Rarity.Common,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 25,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 33,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 41,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 49,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 57,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 65,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 73,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 81,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 89,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 97,
            rarity: Rarity.Uncommon,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 105,
            rarity: Rarity.Mythic,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            description: "Plant species",
            id: 113,
            rarity: Rarity.Uncommon,
        },
    ],

    seeds: [
        {
            tileset: "Allitems",
            name: "Wheat",
            id: 16,
            rarity: Rarity.Common,
            plant: 0,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 24,
            rarity: Rarity.Common,
            plant: 1,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 32,
            rarity: Rarity.Common,
            plant: 2,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 40,
            rarity: Rarity.Common,
            plant: 3,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 48,
            rarity: Rarity.Common,
            plant: 4,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 56,
            rarity: Rarity.Common,
            plant: 5,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 64,
            rarity: Rarity.Common,
            plant: 6,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 72,
            rarity: Rarity.Common,
            plant: 7,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 80,
            rarity: Rarity.Common,
            plant: 8,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 88,
            rarity: Rarity.Common,
            plant: 9,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 96,
            rarity: Rarity.Common,
            plant: 10,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 104,
            rarity: Rarity.Mythic,
            plant: 11,
        },
        {
            tileset: "Allitems",
            name: "Eggplant",
            id: 112,
            rarity: Rarity.Common,
            plant: 12,
        },
    ],
};
