export const TextStyles = {
    title: new PIXI.TextStyle({
        fontFamily: "calibri",
        fontSize: 50,
        align: "center",
        dropShadow: true,
        dropShadowBlur: 6,
        dropShadowDistance: 0,
        fill: ["#fafafa"],
    }),
    buttonText: new PIXI.TextStyle({
        fontFamily: "calibri",
        fontSize: 40,
        align: "center",
        dropShadow: true,
        dropShadowBlur: 3,
        dropShadowDistance: 2,
        dropShadowColor: 0x333333,
        fill: ["#fafafa"],
    }),
    itemCount: new PIXI.TextStyle({
        fontFamily: "calibri",
        fontSize: 35,
        fill: 0xffffff,
        dropShadow: true,
        dropShadowColor: 0x000000,
        dropShadowDistance: 0,
        dropShadowBlur: 15,
    }),
};
